CREATE TABLE ROLE (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(255)
);

CREATE TABLE USER (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  ACCOUNT VARCHAR(255),
  ROLE_ID INT,
  FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID),
  UNIQUE KEY ACCOUNT_UNIQUE (ACCOUNT)
);

CREATE TABLE ARTICLE (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  TITLE VARCHAR(255),
  TEXT VARCHAR(5000),
  AUTHOR_ID INT,
  CREATION_DATE TIMESTAMP DEFAULT NOW(),
  FOREIGN KEY (AUTHOR_ID) REFERENCES USER (ID)
)